from logging.config import fileConfig

from geoalchemy2.alembic_helpers import include_object as _geoalchemy2_include_object
from geoalchemy2.alembic_helpers import render_item
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from sqlmodel import SQLModel

from alembic import context

# Populates SQLModel.metadata with every table class (see app/models/__init__.py).
# The report_data.py Pydantic models (HostedSiteRoutineData etc.) are plain
# BaseModel, not table=True, so they never appear in metadata/migrations.
import app.models  # noqa: F401
from app.core.settings import app_settings

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Database credentials live in .env / the environment, never in alembic.ini.
config.set_main_option("sqlalchemy.url", app_settings.database_url)

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata

# Tables in the live DB that Alembic must never diff or manage:
#
# - A separate tenant/licensing product shares this Postgres project.
#   `tenants`, `license_*`, `entitlements`, `tenant_*`, `audit_log` have zero
#   references anywhere in this codebase (confirmed by grep) — not ours.
# - `user_sessions` is a real FieldCore table (app/models/user_session.py,
#   used by app/services/presence.py) but was never imported into
#   app/models/__init__.py, so it has always lived outside SQLModel.metadata.
#   It's being retired when auth moves to Supabase — leave it alone rather
#   than fixing the import now.
# - `login_audit` is real FieldCore data (app/services/auth.py,
#   management_dashboard.py) managed only via raw SQL by design — never a
#   SQLModel table.
# - `webhooks` collides by name with the other product's table: the live
#   column shape (INTEGER id + SERIAL sequence, a tenant_id column) matches
#   neither FieldCore's `Webhook` model (UUID id, no tenant_id) nor any
#   `scripts/*.sql` migration. FieldCore's own webhook feature may never have
#   actually worked against this table — flagged separately for the team;
#   not something to migrate or fix here.
_FOREIGN_OR_UNMANAGED_TABLES = {
    "tenants",
    "tenant_subscriptions",
    "tenant_licenses",
    "tenant_templates",
    "tenant_operation_logs",
    "tenant_feature_usage_events",
    "tenant_compliance_records",
    "tenant_usage_daily",
    "license_plans",
    "license_products",
    "license_history",
    "entitlements",
    "audit_log",
    "user_sessions",
    "login_audit",
    "webhooks",
}


def include_object(object, name, type_, reflected, compare_to):
    if not _geoalchemy2_include_object(object, name, type_, reflected, compare_to):
        return False
    if type_ == "table" and name in _FOREIGN_OR_UNMANAGED_TABLES:
        return False
    # Any other reflected table absent from our own metadata isn't ours —
    # skip rather than propose dropping it.
    if type_ == "table" and reflected and compare_to is None:
        return False
    return True

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # PostGIS support: skip spatial_ref_sys and other extension-owned
            # objects, and render Geometry columns correctly in autogenerated
            # migrations (see app/models/site.py, technician.py).
            include_object=include_object,
            render_item=render_item,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
