"""add sheq_submissions

Revision ID: 97f73cf72ab8
Revises: 4a1c7e9b2f30
Create Date: 2026-08-05 12:59:36.078006

`--autogenerate` against the live DB surfaced the same category of
pre-existing drift the baseline migration's docstring warns about (GIST index
churn on technicians.current_location/home_base, dropped/altered columns
across access_requests, clients, incident_reports, incident_updates,
incidents, maintenance_schedules, route_patrols, sites, system_settings,
tasks, technician_sites, technicians, template_categories, users — none of it
related to this change). Every operation below except sheq_submissions itself
was hand-removed per SHEQ-CHECKLISTS-PLAN.md §9.3 — this file contains only
`sheq_submissions`'s table and its 6 indexes (2 simple + 4 partial-composite
from `__table_args__`), plus the 2 enum types SQLAlchemy creates inline as
part of `create_table`. No other table is touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97f73cf72ab8'
down_revision: Union[str, Sequence[str], None] = '4a1c7e9b2f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheq_submissions',
    sa.Column('checklist_type', sa.Enum('VEHICLE_DAILY', 'JOURNEY_MANAGEMENT', 'DAILY_RISK_ASSESSMENT', 'TECHNICIAN_MASTER_SAFETY', name='sheqchecklisttype'), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'SIGNED_OFF', name='sheqstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supervisor_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheq_submissions_checklist_type'), 'sheq_submissions', ['checklist_type'], unique=False)
    op.create_index('ix_sheq_submissions_site', 'sheq_submissions', ['site_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_sheq_submissions_status'), 'sheq_submissions', ['status'], unique=False)
    op.create_index('ix_sheq_submissions_task', 'sheq_submissions', ['task_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_sheq_submissions_technician_performed_on', 'sheq_submissions', ['technician_id', sa.literal_column('performed_on DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_sheq_submissions_type_status', 'sheq_submissions', ['checklist_type', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sheq_submissions_type_status', table_name='sheq_submissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_sheq_submissions_technician_performed_on', table_name='sheq_submissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_sheq_submissions_task', table_name='sheq_submissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_sheq_submissions_status'), table_name='sheq_submissions')
    op.drop_index('ix_sheq_submissions_site', table_name='sheq_submissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_sheq_submissions_checklist_type'), table_name='sheq_submissions')
    op.drop_table('sheq_submissions')
    # ### end Alembic commands ###
